In [4]:
import numpy as np

arr= np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [95]:
numList1 = list(map(int, input().split()))[:5]
numList2 = list(map(int, input().split()))[:5]

arr1 = np.array( numList1 )
arr2= np.array(numList2)

arr=arr1+ arr2
print(arr,"\n")

print("after sorting", np.sort(arr))

1 9 2 8 5
3 7 4 6 1
[ 4 16  6 14  6] 

after sorting [ 4  6  6 14 16]


In [92]:
arr=np.array([[23,1,4,5],[672,2,1,25],[66,54,5,44]])
print(np.shape(arr))
print(np.size(arr))

(3, 4)
12


In [91]:
arr= np.array([1,2,3,4,5,6,7,8,9])

print(arr[:, np.newaxis],"\n")

print(np.expand_dims(arr, axis=1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [90]:
nparr= np.array([[1,2,3],[4,5,6]])
nparr2= np.array([[7,8,9],[2,2,2]])

print(np.vstack(nparr),"\n")
print(np.hstack(nparr2))

[[1 2 3]
 [4 5 6]] 

[7 8 9 2 2 2]


In [89]:
arr= np.array([2,5,5,6,6,7,4,8,7,9])
uni= np.unique(arr)
print(uni, "\n")
print("counts =",np.count_nonzero(uni))

[2 4 5 6 7 8 9] 

counts = 7
